package c.client;


/**
* c.client/ResponderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Sunday, 1 June 2014 19:05:54 o'clock CEST
*/

abstract public class ResponderHelper
{
  private static String  _id = "IDL:c.client/Responder:1.0";

  public static void insert (org.omg.CORBA.Any a, Responder that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Responder extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ResponderHelper.id (), "Responder");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Responder read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ResponderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Responder value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Responder narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Responder)
      return (Responder)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ResponderStub stub = new _ResponderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Responder unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Responder)
      return (Responder)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ResponderStub stub = new _ResponderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
