package StockExchange;


/**
* StockExchange/NonExistingStock.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Sunday, 1 June 2014 19:05:54 o'clock CEST
*/

public final class NonExistingStock extends org.omg.CORBA.UserException
{

  public NonExistingStock ()
  {
    super(NonExistingStockHelper.id());
  } // ctor


  public NonExistingStock (String $reason)
  {
    super(NonExistingStockHelper.id() + "  " + $reason);
  } // ctor

} // class NonExistingStock
