package StockExchange;


/**
* StockExchange/Quote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Sunday, 1 June 2014 19:05:54 o'clock CEST
*/

public final class Quote implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String id = null;
  public String price = null;

  public Quote ()
  {
  } // ctor

  public Quote (String _name, String _id, String _price)
  {
    name = _name;
    id = _id;
    price = _price;
  } // ctor

} // class Quote
