package StockExchange;


/**
* StockExchange/ResponderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Sunday, 1 June 2014 19:05:54 o'clock CEST
*/

public interface ResponderOperations 
{
  void push (StockExchange.Quote quote);
} // interface ResponderOperations
