package StockExchange;

/**
* StockExchange/ServerCommunicationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Sunday, 1 June 2014 19:05:54 o'clock CEST
*/

public final class ServerCommunicationHolder implements org.omg.CORBA.portable.Streamable
{
  public StockExchange.ServerCommunication value = null;

  public ServerCommunicationHolder ()
  {
  }

  public ServerCommunicationHolder (StockExchange.ServerCommunication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StockExchange.ServerCommunicationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StockExchange.ServerCommunicationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StockExchange.ServerCommunicationHelper.type ();
  }

}
