module 	StockExchangeD
{
  
  struct Quote{
    string name;
    string id;
    string price;
  };
  
  // Requested stock does not exist.
  exception Invalid_Stock {};
  
  interface Quoter {
 
    Quote getQuote (in string quoteInfo) raises (Invalid_Stock);

  };  
};
