package StockExchange;


/**
* StockExchange/Quoter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Friday, 30 May 2014 20:46:07 o'clock CEST
*/

public interface Quoter extends QuoterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Quoter
