package StockExchange;


/**
* StockExchange/QuoterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Friday, 30 May 2014 20:46:07 o'clock CEST
*/

public interface QuoterOperations 
{
  void getQuoteByName (String stockName);
  void getQuoteByID (String stockID);
} // interface QuoterOperations
