package StockExchange;


/**
* StockExchange/ResponderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Friday, 30 May 2014 20:46:07 o'clock CEST
*/

public interface ResponderOperations 
{
  void respondQuote (float quote);
} // interface ResponderOperations
