package StockExchange.QuoterPackage;


/**
* StockExchange/QuoterPackage/InvalidStockID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Wednesday, 28 May 2014 11:00:38 o'clock CEST
*/

public final class InvalidStockID extends org.omg.CORBA.UserException
{

  public InvalidStockID ()
  {
    super(InvalidStockIDHelper.id());
  } // ctor


  public InvalidStockID (String $reason)
  {
    super(InvalidStockIDHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidStockID
