package StockExchange.QuoterPackage;

/**
* StockExchange/QuoterPackage/InvalidStockNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Saturday, 24 May 2014 15:04:29 o'clock CEST
*/

public final class InvalidStockNameHolder implements org.omg.CORBA.portable.Streamable
{
  public StockExchange.QuoterPackage.InvalidStockName value = null;

  public InvalidStockNameHolder ()
  {
  }

  public InvalidStockNameHolder (StockExchange.QuoterPackage.InvalidStockName initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StockExchange.QuoterPackage.InvalidStockNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StockExchange.QuoterPackage.InvalidStockNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StockExchange.QuoterPackage.InvalidStockNameHelper.type ();
  }

}
