/*
 * Generated by 1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "Assignment2"
 * 	found in "./CCompiler/tryouts.asn"
 */

#ifndef	_ClientServer_H_
#define	_ClientServer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ClientServer */
typedef struct ClientServer {
	long	 binaryCodedInteger;
	PrintableString_t	 randomStringOrVerification;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ClientServer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ClientServer;

#ifdef __cplusplus
}
#endif

#endif	/* _ClientServer_H_ */
