package a.server;


/**
* /QuoterPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Wednesday, 28 May 2014 11:00:38 o'clock CEST
*/

public class QuoterPOATie extends QuoterPOA
{

  // Constructors

  public QuoterPOATie ( QuoterOperations delegate ) {
      this._impl = delegate;
  }
  public QuoterPOATie ( QuoterOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public QuoterOperations _delegate() {
      return this._impl;
  }
  public void _delegate (QuoterOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public float getQuoteByName (String stockName) throws QuoterPackage.InvalidStockName
  {
    return _impl.getQuoteByName(stockName);
  } // getQuoteByName

  public float getQuoteByID (String stockID) throws QuoterPackage.InvalidStockID
  {
    return _impl.getQuoteByID(stockID);
  } // getQuoteByID

  private QuoterOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class QuoterPOATie
