package StockExchange;


/**
* StockExchange/QuoterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Wednesday, 28 May 2014 11:00:38 o'clock CEST
*/

public interface QuoterOperations 
{
  float getQuoteByName (String stockName) throws StockExchange.QuoterPackage.InvalidStockName;
  float getQuoteByID (String stockID) throws StockExchange.QuoterPackage.InvalidStockID;
} // interface QuoterOperations
