package StockExchange;


/**
* StockExchange/QuoterPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
* Wednesday, 28 May 2014 11:00:38 o'clock CEST
*/

public class QuoterPOATie extends QuoterPOA
{

  // Constructors

  public QuoterPOATie ( StockExchange.QuoterOperations delegate ) {
      this._impl = delegate;
  }
  public QuoterPOATie ( StockExchange.QuoterOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public StockExchange.QuoterOperations _delegate() {
      return this._impl;
  }
  public void _delegate (StockExchange.QuoterOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public float getQuoteByName (String stockName) throws StockExchange.QuoterPackage.InvalidStockName
  {
    return _impl.getQuoteByName(stockName);
  } // getQuoteByName

  public float getQuoteByID (String stockID) throws StockExchange.QuoterPackage.InvalidStockID
  {
    return _impl.getQuoteByID(stockID);
  } // getQuoteByID

  private StockExchange.QuoterOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class QuoterPOATie
